import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./providers/NextAuthProvider";
import { Toaster } from "react-hot-toast";
import ReactQueryClientProvider from "./providers/ReactQueryClientProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shaqo Sahal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <ReactQueryClientProvider>
          <NextAuthProvider>
            <main className="h-full">
              {children}
              <Toaster />
            </main>
          </NextAuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
